SET foreign_key_checks = 0;
DELETE from `users`;
DELETE from `user_roles`;
DELETE from `posts`;
DELETE from `tags`;
DELETE from `post_tags`;
INSERT INTO `users` (id, user_name, password, email, last_name, first_name) VALUES (1,'jpublic','secretpw1','jpublic@wisc.edu','Public', 'John'),(2,'kmalone','secretpw2','kmalone@jazz.com','Malone', 'Karl'),(3,'dduany','secretpw3','dduany@wisc.edu','Duany', 'Duany'),(4,'hcoulson','secretpw4','hcoulson@hotmail.com','Coulson', 'Hannah'),(5,'szawistowski','secretpw5','sz01@wisc.edu','Zawistowski', 'Samantha'),(6,'bcurry','secretpw6','bcurry@hotmail.com','Curry', 'Barney'),(7,'hc98','secretpw7','hannahbanannah@hotmail.com','Coulson', 'Hannah');
INSERT INTO `user_roles` (id, user_name, role_name) VALUES (1,'bcurry', 'admin'),(2,'szawistowski', 'admin'),(3,'hcoulson', 'user'),(4,'dduany', 'user'),(5,'kmalone', 'user'),(6,'jpublic', 'user'), (7, 'kmalone', 'admin');
INSERT INTO `posts` (id, title, video_url, description_body, user_id) VALUES (1, 'My cat paws endlessly at the mirror', 'https://www.youtube.com/watch?v=fakeurl2', 'My cat paws incessantly at the mirror. What does this mean?', 1), (2, 'Flops down on the floor at my feet and rolls around', 'https://www.youtube.com/watch?v=fakeurl99', 'Lately, my cat will do this thing where she flops down on the floor right at my feet and rolls around. What\'s with this goofy behavior?', 2), (3, 'Meowing endlessly at the door', 'https://www.youtube.com/watch?v=fakeurl4', 'My cats have taken to meowing at any and all closed doors in the house. They', 4), (4, 'Meowing endlessly at the door', 'https://www.youtube.com/watch?v=fakeurl4', 'Our kitten starts howling at the front door each night at exactly 8:15PM. What the heck?', 2);
SET foreign_key_checks = 1;
